[package]
name = "towns-protocol-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
alloy = {workspace = true}
alloy-sol-macro = {workspace = true}